baseURL = 'https://imswat.com'
languageCode = 'hu'
title = 'IMSWAT REBORNED'
theme = 'hugo-cat'

enableEmoji = true
PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
watch = true

[params]
ava = "img/IMSWAT.png"
#owner = "Since 2011"
talk = "Since 2011"
favicon = "img/IMSWAT.png"

[[menu.main]]
name = "TeamSpeak"
url = "https://imswat.com/ts"
weight = 10

[[menu.main]]
name = "MOHAA"
url = "/mohaa"
weight = 11

[[menu.main]]
name = "WoW Guild"
url = "https://raider.io/guilds/eu/arathor/imswat"
weight = 12

[[menu.main]]
name = "YouTube"
url = "https://imswat.com/yt"
weight = 15

[[menu.main]]
name = "Stats"
url = "https://stats.imswat.com"
weight = 30

[[menu.main]]
name = "Uptime"
url = "https://uptime.imswat.com"
weight = 40

[[menu.main]]
name = "Blog"
url = "/soon"
weight = 50
