baseURL = 'https://imswat.com'
languageCode = 'hu'
title = 'IMSWAT REBORNED'
theme = 'hugo-cat'

enableEmoji = true
PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
watch = true

[params]
ava = "img/IMSWAT.png"
#owner = "Since 2011"
talk = "Since 2011"
favicon = "img/IMSWAT.png"

[[menu.main]]
name = "TeamSpeak"
url = "https://imswat.com/ts"
weight = 10
target = "_blank"

[[menu.main]]
name = "YouTube"
url = "https://imswat.com/yt"
weight = 10
post = "target='_BLANK'"

[[menu.main]]
name = "Stats"
url = "https://stats.imswat.com"
weight = 30

[[menu.main]]
name = "Uptime"
url = "https://uptime.imswat.com"
weight = 40

[[menu.main]]
name = "Blog"
url = "/soon"
weight = 50
